print('Задание 1')
print('Glo Academy')
print()
print('Glo Academy')
print('Glo Academy', 'Glo Academy', sep='\n\n')

print()
print('Задание 2')
print('Как тебя зовут?')
name = input()
print('Привет, ', name)

print()
print('Задание 3')
print('Как тебя зовут?')
name = input()
print('Как ваша фамилия?')
surname = input()
print('Как ваше отчество?')
patronymic = input()
print('Привет, ', name, '-' , surname, '-', patronymic, sep='')